service: instachecker

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  check_stores:
    handler: instachecker.handlers.check_stores
    events:
    - schedule: cron(0,30 * * * ? *)

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true

plugins:
  - serverless-python-requirements
